drop table if exists users;

create table if not exists users (
user_id bigint generated by default as identity primary key,
email varchar(60) not null unique,
name varchar(100) not null
);

create unique index if not exists email_idx on users (email);