drop table if exists users, categories;

create table if not exists users (
user_id bigint generated by default as identity primary key,
email varchar(60) not null unique,
name varchar(100) not null
);

create unique index if not exists email_idx on users (email);

create table if not exists categories (
category_id bigint generated by default as identity primary key,
category_name varchar(50) not null unique
);

create unique index if not exists category_name_idx on categories (category_name);