drop table if exists users, categories, events;

create table if not exists users (
user_id bigint generated by default as identity primary key,
email varchar(60) not null unique,
name varchar(100) not null
);

create unique index if not exists email_idx on users (email);

create table if not exists categories (
category_id bigint generated by default as identity primary key,
category_name varchar(50) not null unique
);

create unique index if not exists category_name_idx on categories (category_name);

create table if not exists events (
event_id bigint generated by default as identity primary key,
title varchar(100) not null,
annotation varchar(255) not null,
description_ev varchar(3000) not null,
event_date timestamp without time zone not null,
category_id bigint not null,
state_ev varchar(15) check(state_ev in ('PENDING', 'PUBLISHED', 'CANCELED')) not null,
created_on timestamp without time zone not null,
published_on timestamp without time zone,
lat double precision not null,
lon double precision not null,
paid boolean not null,
participant_limit int not null,
request_moderation boolean not null,
initiator_id bigint not null,

constraint fk_category_id foreign key (category_id) references categories (category_id),
constraint fk_initiator_id foreign key (initiator_id) references users (user_id)
);

create index if not exists event_date_idx on events (event_date);
create index if not exists category_id_idx on events (category_id);
create index if not exists state_ev_idx on events (state_ev);
create index if not exists paid_idx on events (paid);
create index if not exists participant_limit_idx on events (participant_limit);
create index if not exists initiator_id_idx on events (initiator_id);