drop table if exists hits;

create table if not exists hits(
id bigint generated by default as identity primary key not null,
app varchar(64) not null,
uri varchar(64) not null,
ip varchar(64) not null,
timestamp TIMESTAMP without time zone not null
);

create index if not exists hits_app_uri_idx on hits(app, uri);