drop table if exists endpoint_hits;

create table if not exists endpoint_hits(
id bigint generated by default as identity primary key,
app varchar(100) not null,
uri varchar(255) not null,
ip varchar(60) not null,
timestamp timestamp without time zone not null);

create index if not exists endpoint_hits_app_uri_idx on endpoint_hits(app, uri);