services:
  stats-server:
    build: stats-service
    image: stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ewm-network

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-postgres
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres/stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - ewm-network

  ewm-service:
    build: ewm-service
    image: ewm-server
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - STATS_SERVER_URL=http://stats-server:9090
    networks:
      - ewm-network

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-postgres
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/postgres/ewm:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge