drop table if exists endpoint_hits;

create table endpoint_hits(
id bigint generated by default as identity primary key,
app varchar(100) not null,
uri varchar(255) not null,
ip varchar(30) not null,
timestamp timestamp without time zone not null
);