drop table if exists endpoint_hits;

create table if not exists endpoint_hits(
id bigint generated by default as identity primary key,
app varchar(255) not null,
uri varchar(1000) not null,
ip varchar(50) not null,
timestamp timestamp without time zone not null,

CREATE INDEX idx_timestamp ON endpoint_hits(timestamp);
CREATE INDEX idx_uri ON endpoint_hits(uri);
);